name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - rickydodd
body:
  - type: markdown
    attributes:
      value: |
        Please try to be as descriptive as possible about your setup, what bug occurred, and what you think should have occurred instead. Thank you for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened? And what did you expect to happen?
      placeholder: "[blank] occurred, when I expected [blank] to occur instead."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste log output. This will automatically be formatted into code, so no need to include backticks around the output.
      render: shell
