name: CI
on:
  # workflow_call is a required field of the "on" property,
  #when intending to use the workflow as a reusable workflow
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build application
        run: go build -o api ./cmd/...
